name: Run tests and linters on push
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-tags: True

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir -r ./app/requirements.txt

      - name: Install linters
        run: |
          python -m pip install black~=24.4

      - name: Lint Python code with black
        run: |
          black --check --verbose --skip-string-normalization --line-length 120 app

      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
          ignore: DL3008,SC3009,DL3013

      - name: Run tests
        run: |
          cd app
          pwd
          python test_qrgen.py
